package HolaMundoApp;

/**
* HolaMundoApp/HolaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from holamundo.idl
* Wednesday, October 9, 2013 2:36:14 PM CEST
*/

public final class HolaHolder implements org.omg.CORBA.portable.Streamable
{
  public HolaMundoApp.Hola value = null;

  public HolaHolder ()
  {
  }

  public HolaHolder (HolaMundoApp.Hola initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HolaMundoApp.HolaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HolaMundoApp.HolaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HolaMundoApp.HolaHelper.type ();
  }

}
