package HolaMundoApp;


/**
* HolaMundoApp/Hola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from holamundo.idl
* Wednesday, October 9, 2013 2:36:14 PM CEST
*/

public interface Hola extends HolaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hola
