package HolaMundoApp;


/**
* HolaMundoApp/HolaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from holamundo.idl
* Wednesday, October 9, 2013 2:36:14 PM CEST
*/

public interface HolaOperations 
{
  String decirHola ();
} // interface HolaOperations
